<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Google.Solutions.Tsc</RootNamespace>
    <AssemblyName>Google.Solutions.Tsc</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="AxMSTSCLib">
      <Guid>{8C11EFA1-92C3-11D1-BC1E-00C04FA31489}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>aximp</WrapperTool>
      <Isolated>False</Isolated>
    </COMReference>
    <COMReference Include="MSTSCLib">
      <Guid>{8C11EFA1-92C3-11D1-BC1E-00C04FA31489}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
</Project>